<?php
declare(strict_types=1);
require dirname(__DIR__) . '/backend/bootstrap.php';
start_session();
header('Cache-Control: no-store');
header('X-Frame-Options: DENY');
try { $user = current_user(); } catch (Throwable $error) { error_log($error->getMessage()); http_response_code(503); exit('The club service is temporarily unavailable. Please try again shortly.'); }
if (!$user) { header('Location: login.php'); exit; }
if ($user['role'] === 'admin') { header('Location: ../admin/index.php'); exit; }
if ($user['role'] !== 'user') { http_response_code(403); exit('This area is for club members. Please contact the club administrator for staff access.'); }
?>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="csrf-token" content="<?= escape($_SESSION['csrf']) ?>"><title>My account — FORM</title><link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="style.css"><script src="script.js" defer></script></head>
<body class="member-page">
<a class="skip-link" href="#member-content">Skip to content</a>
<header class="member-header"><a class="logo" href="../index.html"><span class="logo-mark" aria-hidden="true">ƒ</span> FORM<span class="logo-caption">FITNESS CLUB</span></a><a class="back-to-club" href="../index.html">Back to the club ↗</a><form method="post" action="logout.php"><input type="hidden" name="csrf" value="<?= escape($_SESSION['csrf']) ?>"><button type="submit" class="member-signout">Sign out</button></form></header>
<div class="member-layout"><aside class="member-sidebar"><p class="eyebrow">YOUR SPACE</p><nav aria-label="Member account"><a href="#overview" aria-current="page"><span>01</span> Overview</a><a href="#schedule"><span>02</span> Schedule</a><a href="#bookings"><span>03</span> My bookings</a><a href="#profile"><span>04</span> My profile</a></nav><a class="member-review" href="../index.html#review-form">Share your story ↗</a><p class="sidebar-note">A little stronger.<br>Every day.</p></aside>
<main id="member-content" class="member-main">
<p id="member-status" class="form-status" role="status" aria-live="polite">Loading your account…</p><button id="retry-load" class="button button--outline" hidden>Try again</button>
<section data-section="overview"><p class="eyebrow">YOUR ROUTINE / YOUR SPACE</p><h1>Hey, <span id="member-name"><?= escape($user['name']) ?></span>.<br>Keep your <em>rhythm.</em></h1><p class="member-lead">Your membership and next class, all in one place.</p><div class="member-cards"><article class="member-card"><p class="eyebrow">UP NEXT</p><div id="next-class"><p>Loading your next class…</p></div></article><article class="member-card membership-card"><p class="eyebrow">YOUR MEMBERSHIP</p><div id="membership"><p>Loading your membership…</p></div></article></div><div class="member-callout"><div><h2>Make time for your next move.</h2><p>Find a class that fits your day.</p></div><a class="button" href="#schedule">Find a class ↗</a></div></section>
<section data-section="schedule" hidden><p class="eyebrow">MAKE TIME TO MOVE</p><h1>Your next <em>move.</em></h1><p class="member-lead">Choose a date and save your spot. All times are local to the club.</p><div class="schedule-toolbar"><label for="schedule-date">Class date<input type="date" id="schedule-date" required></label><span class="field-hint">Book up to 28 days ahead.</span></div><p id="schedule-status" class="form-status" role="status"></p><div id="class-list" aria-busy="true"></div></section>
<section data-section="bookings" hidden><p class="eyebrow">SHOW UP FOR YOURSELF</p><h1>My <em>bookings.</em></h1><p class="member-lead">A little commitment goes a long way.</p><h2 class="list-heading">Coming up</h2><div id="upcoming-bookings"></div><h2 class="list-heading history-heading">Past & cancelled</h2><div id="past-bookings"></div></section>
<section data-section="profile" hidden><p class="eyebrow">A LITTLE ABOUT YOU</p><h1>My <em>profile.</em></h1><div class="profile-grid"><form class="stacked-form member-card" id="profile-form"><h2>Your details</h2><label>Name<input name="name" maxlength="100" autocomplete="name" value="<?= escape($user['name']) ?>" required></label><label>Email address<input name="email" type="email" maxlength="200" autocomplete="email" value="<?= escape($user['email']) ?>" required></label><label>Current password<input name="current_password" type="password" maxlength="72" autocomplete="current-password" required></label><p class="field-hint">Confirm your password to update your details.</p><p class="form-status" role="status"></p><button class="button" type="submit">Save changes ↗</button></form><form class="stacked-form member-card" id="password-form"><h2>Change password</h2><label>Current password<input name="current_password" type="password" maxlength="72" autocomplete="current-password" required></label><label>New password<input name="new_password" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><label>Confirm new password<input name="password_confirmation" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><p class="field-hint">Use 12–72 characters.</p><p class="form-status" role="status"></p><button class="button button--outline" type="submit">Update password ↗</button></form></div></section>
<noscript><p>Please enable JavaScript to view classes and manage your account.</p></noscript>
</main></div><footer class="member-footer">FORM Fitness Club / A little stronger. Every day.</footer>
<dialog id="cancel-dialog" class="member-dialog" aria-labelledby="cancel-title"><h2 id="cancel-title">Cancel your booking?</h2><p id="cancel-description"></p><p class="form-status" id="cancel-status" role="status"></p><div class="dialog-actions"><button class="button button--outline" id="keep-booking" type="button">Keep my spot</button><button class="button" id="confirm-cancel" type="button">Cancel booking</button></div></dialog>
</body></html>
